"""Generate the coaching/front-office curation PROPOSALS workbook.

Output: data/scheme/curation/coaching_curation_proposals.xlsx

Same 4-tab schema as coaching_curation.xlsx, but every proposed value
is RED (color="C00000") so Brett can quickly distinguish what the
agent suggested vs. his canonical DET row (BLACK).

Each tab includes a final `_confidence` column:
  high              — PFR / team site direct hit (training-confident through Jan 2026)
  med               — multiple reporting sources agree (training-confident, low risk of late churn)
  low               — single source or stale
  judgment_needed   — subjective columns (signature concepts, identity); blank value
  (blank)           — fact unknown; cell left blank

DET row is filled in BLACK from Brett's canonical example (NOT a proposal).

Re-run safely; overwrites the file.
"""
from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "data" / "scheme" / "curation" / "coaching_curation_proposals.xlsx"

TEAMS = [
    "ARI", "ATL", "BAL", "BUF", "CAR", "CHI", "CIN", "CLE",
    "DAL", "DEN", "DET", "GB",  "HOU", "IND", "JAX", "KC",
    "LA",  "LAC", "LV",  "MIA", "MIN", "NE",  "NO",  "NYG",
    "NYJ", "PHI", "PIT", "SEA", "SF",  "TB",  "TEN", "WAS",
]

HEADER_FILL = PatternFill("solid", fgColor="0a3d62")
HEADER_FONT = Font(bold=True, color="FFFFFF", size=11)
TITLE_FILL = PatternFill("solid", fgColor="0076B6")
TITLE_FONT = Font(bold=True, color="FFFFFF", size=14)
EXAMPLE_FILL = PatternFill("solid", fgColor="FFF8DC")
THIN = Side(style="thin", color="B0B7BC")
CELL_BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

# Red for all proposed (agent-generated) values. DET row stays default black.
PROPOSAL_FONT = Font(color="C00000")


# ---------------------------------------------------------------------------
# DATA — built from training knowledge (cutoff Jan 2026). Every row tagged
# with confidence. Subjective fields use "judgment_needed" + blank value
# unless we are training-confident (high agreement in coverage).
# ---------------------------------------------------------------------------

# ----- HEAD COACHES ---------------------------------------------------------
# Tab 1 columns: Name, Years, System, Tree, Mentor, Path, Leadership,
#                4th-down, GameMgmt, ActsAsOC, ActsAsDC, SigMoment,
#                OneLiner, Notes, _confidence
HC = {
    "ARI": (
        "Jonathan Gannon",
        "4 (2023-)",
        "Defensive-minded, Vic Fangio coverage roots",
        "Fangio tree (via PHI DC stint)",
        "Vic Fangio",
        "MIN/IND scout asst → TEN/IND DB → PHI DC → ARI HC",
        "Even-keeled, occasionally fiery (Brissett incident 2023)",
        "Moderate-to-aggressive on 4th down",
        "Mid-pack game-management reputation",
        "No", "No",
        "2024 NFC West contention with Kyler/Conner core",
        "Defensive HC trying to install Fangio principles in the desert.",
        "",
        "med",
    ),
    "ATL": (
        "Raheem Morris",
        "2 (2024-)",
        "Player-led, defensive-minded, multiple-scheme defense",
        "Shanahan tree (LA DC) / Tampa-2 roots",
        "Mike Shanahan / Kyle Shanahan",
        "TB DB → TB HC interim → ATL DC → WAS DC → LA DC → ATL HC",
        "Players' coach, high-EQ communicator",
        "Moderate",
        "Solid; veteran coach reputation",
        "No", "No",
        "Hired Penix, transitioned from Cousins; 2024-25 rebuild",
        "Veteran defensive coach back in Atlanta after Rams DC stop.",
        "",
        "high",
    ),
    "BAL": (
        "John Harbaugh",
        "19 (2008-)",
        "Special-teams-rooted, run-heavy, RPO/Lamar offense",
        "Harbaugh tree (root)",
        "Andy Reid (PHI mentor)",
        "PHI special teams → BAL HC",
        "Demanding, structured, religiously disciplined",
        "Aggressive (top-tier 4th-down go rates)",
        "Strong; one of the league's best",
        "No", "No",
        "SB XLVII champion (2012); multiple AFC title runs",
        "Longest-tenured AFC HC; built around Lamar Jackson era.",
        "",
        "high",
    ),
    "BUF": (
        "Sean McDermott",
        "9 (2017-)",
        "Defensive-minded, pattern-match coverage, Quarters",
        "Andy Reid / Jim Johnson tree",
        "Jim Johnson",
        "PHI DB → PHI DC → CAR DC → BUF HC",
        "Process-oriented, structured",
        "Moderate (improved over tenure)",
        "Mixed — '13 seconds' game cited as cautionary",
        "No", "Yes (calls defense)",
        "Multiple AFC East titles in Allen era",
        "Long-tenured McDermott era; Allen-led offense, McDermott-led D.",
        "",
        "high",
    ),
    "CAR": (
        "Dave Canales",
        "3 (2024-)",
        "QB-whisperer offensive-minded HC; Shanahan-adjacent passing game",
        "Pete Carroll / Shanahan-adjacent",
        "Pete Carroll",
        "SEA QC/QB → SEA OC (1 yr) → TB OC → CAR HC",
        "Players' coach, energy-driven",
        "Moderate",
        "Developing reputation",
        "Yes (offensive architect, OC oversight)", "No",
        "Bryce Young revival in 2024-25 second half",
        "Offensive QB-developer brought in to fix Bryce Young.",
        "",
        "high",
    ),
    "CHI": (
        "Ben Johnson",
        "2 (2025-)",
        "Shanahan-WCO with motion, condensed sets, RPO/play-action",
        "Shanahan tree (via DET) / Lions OC pedigree",
        "Dan Campbell / Sean McVay-adjacent influence",
        "BOS College asst → MIA QC → DET WR/TE/QB → DET OC → CHI HC",
        "Cerebral, detail-driven, schematically aggressive",
        "Aggressive on 4th down (DET legacy)",
        "Untested at HC; analytics-leaning by reputation",
        "Yes (offensive architect, calls plays)", "No",
        "Drafted to develop Caleb Williams",
        "DET OC turned Bears HC; tasked with unlocking Caleb Williams.",
        "",
        "high",
    ),
    "CIN": (
        "Zac Taylor",
        "8 (2019-)",
        "McVay-tree spread passing, 11 personnel base",
        "McVay tree / Shanahan tree",
        "Sean McVay",
        "MIA QB → LA assistant → LA QB → CIN HC",
        "Calm, players-first",
        "Moderate",
        "Mixed; criticized for clock management",
        "Yes (calls plays / heavy OC influence)", "No",
        "AFC Championship 2021 (Super Bowl LVI)",
        "McVay disciple paired with Burrow for the Bengals' modern era.",
        "",
        "high",
    ),
    "CLE": (
        "Kevin Stefanski",
        "7 (2020-)",
        "Shanahan WCO, outside zone, 13 personnel sub-packages",
        "Shanahan tree (via MIN) / Kubiak run game",
        "Gary Kubiak / Kyle Shanahan",
        "MIN asst → MIN OC → CLE HC",
        "Even-keeled, schematic",
        "Moderate",
        "Solid",
        "Yes (calls plays in most years)", "No",
        "2x Coach of the Year (2020, 2023); 2020 playoff win",
        "WCO-rooted HC who has weathered Watson era; play-caller HC.",
        "",
        "high",
    ),
    "DAL": (
        "Brian Schottenheimer",
        "2 (2025-)",
        "Coryell-rooted vertical passing, Shanahan-adjacent run game",
        "Coryell/Schottenheimer tree (lineage)",
        "Marty Schottenheimer (father) / Mike Holmgren",
        "WAS/STL/NYJ/SEA/JAX/SEA OC → DAL OC → DAL HC",
        "Veteran coordinator promoted internally",
        "Unknown (limited HC sample)",
        "Limited HC sample",
        "Yes (offensive architect)", "No",
        "Internal promotion after McCarthy departure",
        "Long-time NFL OC promoted from within Dallas under Jerry Jones.",
        "",
        "high",
    ),
    "DEN": (
        "Sean Payton",
        "4 (2023-)",
        "Coryell-influenced WCO hybrid, RB+TE-friendly, multiple personnel",
        "Coryell/Payton tree (root)",
        "Bill Parcells / Jon Gruden",
        "Multiple QB coach jobs → DAL OC → NO HC → DEN HC",
        "Demanding, alpha play-caller",
        "Aggressive on 4th down (Saints legacy)",
        "Strong (HOF-track)",
        "Yes (offensive architect, calls plays)", "No",
        "SB XLIV champion (NO); 2024 Bo Nix playoff push (DEN)",
        "Future HOF play-caller running the Bo Nix era in Denver.",
        "",
        "high",
    ),
    "DET": None,  # filled in BLACK from Brett's canonical row below
    "GB": (
        "Matt LaFleur",
        "8 (2019-)",
        "Shanahan WCO, outside zone, condensed sets, motion",
        "Shanahan tree / McVay-adjacent",
        "Kyle Shanahan / Sean McVay",
        "WAS QC → ATL QB → LA OC → TEN OC → GB HC",
        "Even-keeled, scheme-driven",
        "Moderate",
        "Solid",
        "Yes (offensive architect, calls plays)", "No",
        "Multiple NFC North titles, Jordan Love development",
        "Shanahan-rooted HC; designed system to outlive Rodgers and grow Love.",
        "",
        "high",
    ),
    "HOU": (
        "DeMeco Ryans",
        "4 (2023-)",
        "Defensive-minded, 4-3 / Wide-9 attack front, single-high coverage",
        "Shanahan tree (defensive side) / Saleh lineage",
        "Robert Saleh",
        "SF ILB → SF DC → HOU HC",
        "Players' coach, defensive intensity",
        "Moderate",
        "Strong young HC reputation",
        "No", "Yes (heavy defensive influence)",
        "Won AFC South in Year 1 (2023); Stroud development",
        "Saleh-tree defensive HC paired with Stroud's offense.",
        "",
        "high",
    ),
    "IND": (
        "Shane Steichen",
        "4 (2023-)",
        "Spread RPO offense with mobile-QB lean",
        "Reid/McVay hybrid (via PHI/LAC)",
        "Frank Reich",
        "SD/LAC OC asst → LAC OC → PHI OC → IND HC",
        "Calm, offense-first",
        "Moderate",
        "Mixed under Anthony Richardson era",
        "Yes (offensive architect)", "No",
        "Hurts dev (PHI) → Richardson (IND) project",
        "Mobile-QB offensive HC tied to Richardson/Jones project.",
        "",
        "high",
    ),
    "JAX": (
        "Liam Coen",
        "2 (2025-)",
        "Shanahan-McVay WCO with vertical play-action shots",
        "McVay/Shanahan tree (via LA + TB)",
        "Sean McVay",
        "LA asst → KY OC → LA OC → TB OC → JAX HC",
        "Cerebral, schematically forward",
        "Unknown (limited HC sample)",
        "Untested",
        "Yes (offensive architect, calls plays)", "No",
        "Hired off TB OC season; Trevor Lawrence reset",
        "McVay-tree OC promoted to fix Trevor Lawrence and the Jags offense.",
        "",
        "high",
    ),
    "KC": (
        "Andy Reid",
        "13 (2013-)",
        "West Coast Offense w/ Coryell vertical concepts; condensed/jet motion",
        "Reid tree (root) / Holmgren-Walsh",
        "Mike Holmgren",
        "GB asst → PHI HC → KC HC",
        "Players' coach, paternal, schematic genius",
        "Moderate (varies by situation)",
        "Strong (HOF-track)",
        "Yes (offensive architect; with Nagy/Bieniemy/Nagy lineage of OCs)", "No",
        "3x SB champion (LIV, LVII, LVIII); Mahomes era dynasty",
        "HOF-track HC with Mahomes, defining the modern WCO era.",
        "",
        "high",
    ),
    "LA": (
        "Sean McVay",
        "10 (2017-)",
        "Shanahan/McVay outside-zone WCO, 11 personnel motion-heavy",
        "Shanahan tree (root co-equal)",
        "Kyle Shanahan / Mike Shanahan",
        "TB asst → WAS TE → WAS OC → LA HC",
        "Cerebral, schematically aggressive, players' coach",
        "Aggressive",
        "Strong",
        "Yes (offensive architect, calls plays)", "No",
        "SB LVI champion; 2018 NFC champion",
        "McVay tree's namesake; Stafford-led Shanahan offense in LA.",
        "",
        "high",
    ),
    "LAC": (
        "Jim Harbaugh",
        "3 (2024-)",
        "Power-run, play-action, defensive-mindset HC",
        "Harbaugh tree (Greg Roman lineage)",
        "Bo Schembechler / Jack Harbaugh (father)",
        "IND/SD QB → Stanford HC → SF HC → MICH HC → LAC HC",
        "Alpha intensity, players' coach",
        "Aggressive (play-it-tough mindset)",
        "Strong",
        "No", "No",
        "Michigan natty 2023; LAC turnaround 2024",
        "Power-run, alpha-intensity HC with Roman-style downhill identity.",
        "",
        "high",
    ),
    "LV": (
        "Pete Carroll",
        "2 (2025-)",
        "Cover-3 single-high defensive identity; balanced run-first offense",
        "Carroll tree / Monte Kiffin lineage (defensively)",
        "Monte Kiffin",
        "Multiple NFL DC → NE HC → SC HC → SEA HC → LV HC",
        "Energy-first, players' coach",
        "Moderate",
        "Mixed (clock issues across career)",
        "No", "Yes (heavy defensive influence)",
        "SB XLVIII champion (SEA); multiple NFC titles",
        "Legendary Carroll era continuing in Vegas at age 70+.",
        "",
        "high",
    ),
    "MIA": (
        "Mike McDaniel",
        "5 (2022-)",
        "Shanahan wide-zone WCO with deep pre-snap motion",
        "Shanahan tree (long-time Kyle assistant)",
        "Kyle Shanahan",
        "DEN/HOU/WAS/CLE/ATL/SF asst → SF OC → MIA HC",
        "Quirky, cerebral, schematically inventive",
        "Moderate",
        "Mixed",
        "Yes (offensive architect, calls plays)", "No",
        "2022-23 Tua passing dominance; 2023 playoffs",
        "Shanahan disciple turning MIA into the league's premier outside-zone team.",
        "",
        "high",
    ),
    "MIN": (
        "Kevin O'Connell",
        "5 (2022-)",
        "McVay/Shanahan WCO, 11 personnel, motion + play-action",
        "McVay/Shanahan tree (via LA OC)",
        "Sean McVay",
        "WAS/SF/CLE QB → LA OC → MIN HC",
        "Calm communicator, QB whisperer",
        "Moderate",
        "Strong reputation",
        "Yes (offensive architect, calls plays)", "No",
        "2024 NFC North race; Sam Darnold revival",
        "McVay-tree QB-whisperer running the post-Cousins era for Minnesota.",
        "",
        "high",
    ),
    "NE": (
        "Mike Vrabel",
        "2 (2025-)",
        "Belichick-rooted defensive identity; run-game-first offense",
        "Belichick tree",
        "Bill Belichick",
        "OSU asst → HOU LB → TEN DC → TEN HC → NE HC",
        "Alpha leader, demanding, direct",
        "Moderate",
        "Strong reputation",
        "No", "Yes (heavy defensive influence)",
        "TEN AFC South titles; 2025 NE turnaround",
        "Belichick-tree disciplinarian back in NE to lead the Drake Maye era.",
        "",
        "high",
    ),
    "NO": (
        "Kellen Moore",
        "2 (2025-)",
        "Coryell-McVay hybrid passing, multiple personnel",
        "Coryell tree (DAL) / McVay-adjacent",
        "Jason Garrett / Sean Payton (philosophical)",
        "DAL QB → DAL OC → LAC OC → PHI OC → NO HC",
        "Cerebral, modern-spread thinker",
        "Moderate (untested)",
        "Untested",
        "Yes (offensive architect, calls plays)", "No",
        "PHI Super Bowl LIX OC season; hired NO HC after",
        "Young offensive HC tasked with the post-Carr/post-Payton Saints era.",
        "",
        "high",
    ),
    "NYG": (
        "Brian Daboll",
        "5 (2022-)",
        "Erhardt-Perkins passing with mobile-QB lean",
        "Belichick tree / Erhardt-Perkins",
        "Bill Belichick",
        "NE asst → multiple coordinator stops → BUF OC → NYG HC",
        "Fiery, demanding",
        "Aggressive",
        "Mixed reputation",
        "Yes (heavy offensive influence)", "No",
        "2022 NFC East playoff win; COY 2022",
        "Belichick-tree HC trying to right NYG with Daniel Jones successor era.",
        "Status uncertain — verify whether Daboll survived Jan 2026 carousel.",
        "low",
    ),
    "NYJ": (
        "Aaron Glenn",
        "2 (2025-)",
        "Defensive-minded; pattern-match coverage, multiple fronts",
        "Saints/Patricia tree → Glenn tree",
        "Sean Payton / Dan Campbell",
        "NO DB → DET DC → NYJ HC",
        "Players' coach, intense defensive identity",
        "Untested",
        "Untested",
        "No", "Yes (defensive architect)",
        "DET defensive turnaround 2022-24; NYJ HC hire",
        "Lions DC turned NYJ HC; defensive identity rebuild in NY.",
        "",
        "high",
    ),
    "PHI": (
        "Nick Sirianni",
        "6 (2021-)",
        "Spread/RPO with heavy play-action and tush-push run game",
        "Reid/McVay/Frank Reich hybrid",
        "Frank Reich",
        "KC/SD/IND asst → IND OC → PHI HC",
        "Energetic, players' coach, fiery",
        "Aggressive (top-tier 4th-down)",
        "Mixed",
        "No (delegates OC)", "No",
        "SB LIX champion (2024); SB LVII appearance",
        "Reigning SB champion; tush-push energy with Hurts-led identity.",
        "",
        "high",
    ),
    "PIT": (
        "Mike Tomlin",
        "20 (2007-)",
        "Defensive-minded, 3-4 hybrid; physical run game; QB-flexible offense",
        "Tony Dungy tree / Cover-2 lineage",
        "Tony Dungy",
        "TB DB → MIN DC → PIT HC",
        "Alpha leader, no-nonsense, players' coach",
        "Conservative-to-moderate",
        "Strong",
        "No", "No",
        "SB XLIII champion; never had a losing season",
        "Longest-tenured HC behind Belichick-era; Steeler standard-bearer.",
        "",
        "high",
    ),
    "SEA": (
        "Mike Macdonald",
        "3 (2024-)",
        "Defensive-minded; disguised pressure, hybrid coverage; modern multi-front",
        "Harbaugh/Macdonald tree (via BAL)",
        "John Harbaugh / Wink Martindale",
        "BAL asst → MICH DC → BAL DC → SEA HC",
        "Cerebral, scheme-driven",
        "Moderate",
        "Untested but well-regarded",
        "No", "Yes (defensive architect)",
        "Top-5 BAL D 2023; SEA Year 1 playoff push",
        "Modern defensive HC redefining post-LOB Seattle defense.",
        "",
        "high",
    ),
    "SF": (
        "Kyle Shanahan",
        "10 (2017-)",
        "Shanahan wide-zone WCO; outside zone, 21 personnel, deep play-action",
        "Shanahan tree (root)",
        "Mike Shanahan (father)",
        "TB QC → multiple OCs → ATL OC → SF HC",
        "Cerebral, schematically aggressive, demanding",
        "Aggressive",
        "Mixed (notable late-game clock losses)",
        "Yes (offensive architect, calls plays)", "No",
        "SB LIV/LVIII appearances; multiple NFC titles",
        "Shanahan tree's namesake; defining outside-zone offensive HC.",
        "",
        "high",
    ),
    "TB": (
        "Todd Bowles",
        "5 (2022-)",
        "Defensive-minded; heavy blitz, multiple fronts; Cover-1/2 hybrid",
        "Parcells/Ryan tree (BB/Ryan-adjacent blitz heritage)",
        "Bill Parcells / Bill Belichick",
        "Multiple stops → ARI DC/HC → NYJ HC → TB DC → TB HC",
        "Quiet, cerebral, scheme-led",
        "Moderate",
        "Mixed",
        "No", "Yes (defensive architect)",
        "Multiple NFC South titles in Mayfield era",
        "Blitz-heavy defensive HC anchoring TB through QB transitions.",
        "",
        "high",
    ),
    "TEN": (
        "Brian Callahan",
        "3 (2024-)",
        "Reid/McVay-adjacent passing offense; spread RPO",
        "Reid tree (via CIN OC) / McVay-adjacent",
        "Zac Taylor / Bill Callahan (father)",
        "DEN/DET QB → OAK QB → CIN OC → TEN HC",
        "Calm, schematic",
        "Moderate (limited HC sample)",
        "Untested",
        "Yes (offensive architect)", "No",
        "Hired to develop QB room post-Tannehill",
        "Reid-tree OC turned TEN HC; QB development project.",
        "Verify Callahan retained for 2026 (potential Jan 2026 firing).",
        "low",
    ),
    "WAS": (
        "Dan Quinn",
        "3 (2024-)",
        "Defensive-minded, Seattle-3 lineage with multiple-front evolution",
        "Carroll tree / Saleh-adjacent",
        "Pete Carroll",
        "SF asst → SEA DC → ATL HC → DAL DC → WAS HC",
        "Players' coach, energy-first, defensively rooted",
        "Moderate",
        "Mixed (28-3 game in ATL HC stint)",
        "No", "Yes (defensive influence)",
        "WAS 2024 NFC Championship run with Daniels",
        "Carroll-tree defensive HC paired with Jayden Daniels' rocket-launch year.",
        "",
        "high",
    ),
}

# DET canonical (BLACK font) — verbatim from Brett's example
HC_DET = (
    "Dan Campbell",
    "5 (2021-)",
    "Defensive-minded culture-builder, offensive empowerment",
    "Belichick tree (DC) → Saints culture (Payton)",
    "Sean Payton",
    "MIA TE → DAL → NO TE coach → DET HC",
    "Players' coach, locker-room first",
    "Aggressive (top-3 in 4th-down go rate)",
    "Sometimes too aggressive in -EV spots; owns mistakes publicly",
    "No",
    "No",
    "2024 NFC North title; 15-2 regular season",
    "Lions HC who turned culture around with toughness and offensive empowerment of Ben Johnson.",
    "",
    "high",
)


# ----- OFFENSIVE COORDINATORS ----------------------------------------------
# Tab 2 columns: Name, Years, ArchitectStatus, Passing, Running,
#                Personnel, Pace, QBType, RedZone, Tree, Mentor,
#                SignatureConcepts, OLCoach, OneLiner, Notes, _confidence
OC = {
    "ARI": (
        "Drew Petzing",
        "3 (2023-)",
        "Coordinator runs offense (Gannon = defensive HC)",
        "Spread RPO with mobile-QB design",
        "Multi-scheme zone with QB-run elements",
        "11 personnel base",
        "Moderate",
        "Mobile dual-threat (Kyler Murray)",
        "QB-run / RPO heavy",
        "Kubiak/Stefanski tree (via CLE)",
        "Kevin Stefanski",
        "",
        "Klayton Adams",
        "Mobile-QB OC built around Kyler's RPO/run-game gravity.",
        "",
        "med",
    ),
    "ATL": (
        "Zac Robinson",
        "2 (2024-)",
        "Coordinator runs offense (Morris = defensive HC)",
        "McVay-tree WCO with deep play-action",
        "Outside zone with gap complement",
        "11 personnel base, 12 in red zone",
        "Moderate",
        "Pocket passer with play-action lean (Penix/Cousins)",
        "Heavy play-action / boot",
        "McVay tree (via LA QB)",
        "Sean McVay",
        "",
        "Dwayne Ledford",
        "McVay-disciple OC running ATL's first true WCO install.",
        "",
        "high",
    ),
    "BAL": (
        "Todd Monken",
        "4 (2023-)",
        "Coordinator runs offense (Harbaugh = defensive HC)",
        "Vertical Coryell w/ Lamar-tailored RPO/mobile elements",
        "Greg Roman-derived gap/power + zone complements",
        "11/12 personnel mix",
        "Moderate-to-fast",
        "Mobile dual-threat (Lamar Jackson)",
        "QB-run + tight-set RPO",
        "Coryell/Spurrier tree (UGA OC)",
        "Steve Spurrier",
        "",
        "George Warhop",
        "Vertical-shot OC who unlocked Lamar's MVP-passing dimension.",
        "",
        "high",
    ),
    "BUF": (
        "Joe Brady",
        "3 (2024-)",
        "Coordinator runs offense",
        "Spread RPO with vertical concepts",
        "Outside zone + gap mix",
        "11 personnel base",
        "Up-tempo, no-huddle capable",
        "Mobile dual-threat (Josh Allen)",
        "QB-run / play-action",
        "Saints/LSU lineage / Payton-adjacent",
        "Sean Payton / Joe Burrow LSU year",
        "",
        "Aaron Kromer",
        "Young OC tasked with maximizing Allen as a dual-threat MVP.",
        "",
        "high",
    ),
    "CAR": (
        "",
        "",
        "HC = architect (Dave Canales runs offense)",
        "Carroll/Shanahan-adjacent passing",
        "Outside zone with power-counter",
        "11 personnel",
        "Moderate",
        "Pocket passer with play-action (Bryce Young)",
        "",
        "Pete Carroll tree",
        "Pete Carroll",
        "",
        "",
        "Canales calls plays; OC role supports Bryce Young development.",
        "OC of record TBD; Canales is offensive architect.",
        "low",
    ),
    "CHI": (
        "Declan Doyle",
        "1 (2025-)",
        "HC = architect (Ben Johnson calls plays)",
        "Shanahan WCO with motion / condensed",
        "Outside zone primary",
        "11/12 mix with motion",
        "Moderate",
        "Pocket-mobile (Caleb Williams)",
        "Condensed-set creativity",
        "Shanahan tree (via DET)",
        "Ben Johnson",
        "",
        "",
        "Ben Johnson is the architect; Doyle administers the room.",
        "OC role configuration may evolve; Johnson calls plays.",
        "med",
    ),
    "CIN": (
        "Dan Pitcher",
        "2 (2024-)",
        "HC = architect (Zac Taylor calls plays in most years)",
        "McVay WCO with vertical Coryell shots",
        "Outside zone",
        "11 personnel base",
        "Moderate",
        "Pocket passer (Burrow)",
        "Stack/bunch + slot iso",
        "McVay tree (via Taylor)",
        "Zac Taylor",
        "",
        "Frank Pollack",
        "Internal promotion to admin role; Taylor remains play-caller.",
        "",
        "high",
    ),
    "CLE": (
        "Tommy Rees",
        "2 (2025-)",
        "HC = architect (Stefanski calls plays in most years)",
        "WCO with Coryell shot complements",
        "Outside zone primary",
        "12/13 personnel sub-package heavy",
        "Moderate",
        "Pocket passer (Watson/whoever)",
        "TE-heavy red zone",
        "Notre Dame/Bama lineage",
        "Kevin Stefanski",
        "",
        "Andy Dickerson",
        "Young OC paired with Stefanski's WCO administration.",
        "",
        "med",
    ),
    "DAL": (
        "Klayton Adams",
        "1 (2026-)",
        "HC = architect (Schottenheimer is offensive HC)",
        "Coryell vertical with WCO underneath",
        "Multiple zone/gap mix",
        "11 personnel base",
        "Moderate",
        "Pocket passer (Dak Prescott)",
        "",
        "Coryell/Schottenheimer tree",
        "Brian Schottenheimer",
        "",
        "Mike Solari",
        "OC supporting Schottenheimer offensive identity.",
        "OC of record may differ; verify.",
        "low",
    ),
    "DEN": (
        "Davis Webb",
        "2 (2025-)",
        "HC = architect (Sean Payton calls plays)",
        "Coryell-WCO hybrid; RB+TE-friendly",
        "Multiple personnel run game",
        "11/12 mix",
        "Moderate",
        "Pocket passer with mobility (Bo Nix)",
        "RB-friendly red zone",
        "Payton tree",
        "Sean Payton",
        "",
        "Zach Strief",
        "Payton remains architect; Webb administers room.",
        "OC of record may differ year-to-year; Payton is play-caller.",
        "med",
    ),
    "DET": None,  # canonical row below
    "GB": (
        "Adam Stenavich",
        "4 (2022-)",
        "HC = architect (Matt LaFleur calls plays)",
        "Shanahan WCO with motion",
        "Outside zone primary",
        "11 personnel base",
        "Moderate",
        "Pocket passer with mobility (Jordan Love)",
        "Play-action shot plays",
        "Shanahan tree (via LAF)",
        "Matt LaFleur",
        "",
        "Luke Butkus",
        "OC working under LaFleur, oversees OL background.",
        "",
        "high",
    ),
    "HOU": (
        "Nick Caley",
        "1 (2025-)",
        "Coordinator runs offense (Ryans = defensive HC)",
        "McVay/Belichick hybrid passing; vertical play-action",
        "Outside zone with gap complement",
        "11 personnel base",
        "Moderate",
        "Pocket passer (CJ Stroud)",
        "TE-flex red zone",
        "Belichick tree (NE) / McVay-adjacent (LA TE)",
        "Bill Belichick / Sean McVay",
        "",
        "Cole Popovich",
        "Belichick/McVay-hybrid OC tasked with Stroud's next leap.",
        "",
        "high",
    ),
    "IND": (
        "",
        "",
        "HC = architect (Shane Steichen calls plays)",
        "Spread RPO with mobile-QB design",
        "Multiple zone schemes with QB run",
        "11 personnel",
        "Moderate-to-fast",
        "Mobile dual-threat (Anthony Richardson / Daniel Jones)",
        "QB-run red zone",
        "Reid/McVay hybrid",
        "Frank Reich / Shane Steichen",
        "",
        "Tony Sparano Jr.",
        "Steichen calls plays; QB-run is the offense's identity.",
        "OC of record TBD/varies.",
        "low",
    ),
    "JAX": (
        "Grant Udinski",
        "1 (2025-)",
        "HC = architect (Liam Coen calls plays)",
        "McVay/Shanahan WCO with vertical shots",
        "Outside zone primary",
        "11 personnel base",
        "Moderate",
        "Pocket passer with mobility (Trevor Lawrence)",
        "Boot/play-action red zone",
        "McVay tree (via Coen)",
        "Liam Coen",
        "",
        "Shawn Jefferson / OL coach TBD",
        "Coen-tree OC supporting Lawrence rebuild.",
        "",
        "med",
    ),
    "KC": (
        "Matt Nagy",
        "4 (2023-)",
        "HC = architect (Andy Reid calls plays)",
        "Reid WCO with Coryell vertical concepts",
        "Inside/outside zone mix",
        "11 personnel base",
        "Moderate",
        "Pocket-mobile (Mahomes)",
        "Jet motion / condensed sets",
        "Reid tree",
        "Andy Reid",
        "",
        "Andy Heck",
        "Returning OC under Reid's umbrella; Reid remains play-caller.",
        "",
        "high",
    ),
    "LA": (
        "Mike LaFleur",
        "2 (2024-)",
        "HC = architect (Sean McVay calls plays)",
        "Shanahan/McVay WCO with motion",
        "Outside zone primary",
        "11 personnel base",
        "Moderate",
        "Pocket passer (Stafford)",
        "Stack/bunch red zone",
        "Shanahan tree (via SF/NYJ)",
        "Kyle Shanahan / Matt LaFleur (brother)",
        "",
        "Ryan Wendell",
        "Brother of GB HC; OC supporting McVay's play-call.",
        "",
        "high",
    ),
    "LAC": (
        "Greg Roman",
        "2 (2024-)",
        "Coordinator runs offense (Jim Harbaugh-aligned)",
        "Power-run play-action passing; gap-heavy",
        "Power gap with pulling linemen; QB-run option",
        "12/13 personnel heavy",
        "Slow, methodical",
        "Mobile dual-threat (Justin Herbert)",
        "Heavy formations + QB run",
        "Harbaugh tree (Roman lineage)",
        "Jim Harbaugh",
        "",
        "Mike Devlin",
        "Run-game architect aligned with Harbaugh's downhill identity.",
        "",
        "high",
    ),
    "LV": (
        "Chip Kelly",
        "2 (2025-)",
        "Coordinator runs offense (Carroll = defensive HC)",
        "Spread/RPO college-ish concepts",
        "Outside zone with QB run",
        "11 personnel base",
        "Up-tempo capable",
        "Mobile-flexible (Geno Smith / Aidan O'Connell)",
        "RPO red zone",
        "Kelly tree (Oregon/PHI/UCLA)",
        "Pete Carroll (current); Kelly's own tree philosophically",
        "",
        "James Cregg",
        "College-spread innovator returning to NFL OC under Carroll.",
        "",
        "high",
    ),
    "MIA": (
        "Frank Smith",
        "5 (2022-)",
        "HC = architect (Mike McDaniel calls plays)",
        "Shanahan wide-zone WCO; pre-snap motion",
        "Outside zone primary",
        "11 personnel base",
        "Up-tempo capable",
        "Pocket passer (Tua)",
        "Motion-driven red zone",
        "Shanahan tree (via SF/MIA)",
        "Mike McDaniel",
        "",
        "Butch Barry",
        "OC working alongside McDaniel; Shanahan-tree lineage.",
        "",
        "high",
    ),
    "MIN": (
        "Wes Phillips",
        "4 (2022-)",
        "HC = architect (Kevin O'Connell calls plays)",
        "McVay WCO with motion",
        "Outside zone primary",
        "11 personnel base",
        "Moderate",
        "Pocket passer (Cousins/Darnold/McCarthy)",
        "Boot/play-action red zone",
        "McVay tree (via LA TE)",
        "Kevin O'Connell",
        "",
        "Chris Kuper",
        "OC under O'Connell; McVay-tree continuity.",
        "",
        "high",
    ),
    "NE": (
        "Josh McDaniels",
        "2 (2025-)",
        "Coordinator runs offense (Vrabel = defensive HC)",
        "Erhardt-Perkins with vertical Coryell elements",
        "Multi-scheme zone/gap mix",
        "12/13 personnel capable",
        "Moderate",
        "Pocket passer (Drake Maye)",
        "Empty / 5-out red zone",
        "Belichick tree / Erhardt-Perkins",
        "Bill Belichick",
        "",
        "Doug Marrone",
        "EP-rooted OC paired with Vrabel; Drake Maye development.",
        "",
        "high",
    ),
    "NO": (
        "Doug Nussmeier",
        "1 (2025-)",
        "HC = architect (Kellen Moore calls plays)",
        "Coryell-McVay hybrid",
        "Multiple zone/gap mix",
        "11 personnel base",
        "Moderate",
        "Pocket passer (Carr/Rattler)",
        "RB+TE red zone",
        "Coryell/McVay hybrid",
        "Kellen Moore",
        "",
        "Brendan Nugent",
        "OC under Moore's offensive umbrella.",
        "OC of record may vary; verify.",
        "med",
    ),
    "NYG": (
        "Mike Kafka",
        "5 (2022-)",
        "HC = architect (Daboll heavy offensive influence)",
        "Erhardt-Perkins with Reid-tree concepts",
        "Multiple zone/gap",
        "11 personnel base",
        "Moderate",
        "Pocket passer (Jones/Wilson successors)",
        "Empty / spread red zone",
        "Reid tree (KC) / Daboll's EP frame",
        "Andy Reid / Brian Daboll",
        "",
        "Carmen Bricillo",
        "Reid-tree OC working under Daboll's offensive structure.",
        "Verify retention through 2026.",
        "low",
    ),
    "NYJ": (
        "Tanner Engstrand",
        "1 (2025-)",
        "Coordinator runs offense (Glenn = defensive HC)",
        "Shanahan WCO (DET lineage); play-action heavy",
        "Outside zone primary",
        "11 personnel base",
        "Moderate",
        "Mobile-flexible (Justin Fields / Tyrod / TBD)",
        "TE-flex red zone",
        "Shanahan tree (via DET)",
        "Ben Johnson / Aaron Glenn",
        "",
        "John Benton",
        "DET-lineage OC importing Lions concepts to NYJ.",
        "",
        "high",
    ),
    "PHI": (
        "Kevin Patullo",
        "1 (2025-)",
        "Coordinator runs offense (Sirianni delegates OC)",
        "Spread RPO with tush-push goal-line identity",
        "Outside zone with gap complement",
        "11 personnel base",
        "Moderate",
        "Mobile dual-threat (Hurts)",
        "Tush-push / RPO red zone",
        "Reid/Reich/Sirianni hybrid",
        "Nick Sirianni / Frank Reich",
        "",
        "Jeff Stoutland",
        "Internal promotion after Moore's NO HC departure.",
        "",
        "high",
    ),
    "PIT": (
        "Arthur Smith",
        "3 (2024-)",
        "Coordinator runs offense (Tomlin = defensive HC)",
        "Shanahan-rooted play-action passing",
        "Outside zone with gap complement; under-center heavy",
        "12/13 personnel heavy",
        "Slow, methodical",
        "Pocket passer (Wilson/Rodgers/etc.)",
        "TE-flex red zone",
        "Shanahan tree (via TEN)",
        "Mike Vrabel (former HC) / Mike Munchak",
        "",
        "Pat Meyer",
        "Run-heavy Shanahan-tree OC paired with Tomlin's defensive HC identity.",
        "",
        "high",
    ),
    "SEA": (
        "Klint Kubiak",
        "2 (2025-)",
        "Coordinator runs offense (Macdonald = defensive HC)",
        "Shanahan/Kubiak WCO with deep play-action",
        "Outside zone primary; under-center heavy",
        "11/12 mix",
        "Moderate",
        "Pocket passer (Sam Darnold)",
        "Boot/play-action red zone",
        "Shanahan tree (Kubiak lineage)",
        "Gary Kubiak (father) / Kyle Shanahan",
        "",
        "John Benton (or successor)",
        "Kubiak-tree OC pairing with Macdonald's defensive HC profile.",
        "",
        "high",
    ),
    "SF": (
        "Klay Kubiak",
        "1 (2025-)",
        "HC = architect (Kyle Shanahan calls plays)",
        "Shanahan wide-zone WCO",
        "Outside zone primary",
        "21/12 personnel heavy",
        "Moderate",
        "Pocket passer (Purdy)",
        "Bunch / motion red zone",
        "Shanahan/Kubiak tree",
        "Kyle Shanahan / Gary Kubiak",
        "",
        "Chris Foerster",
        "Internal promotion under Shanahan; Shanahan calls plays.",
        "Verify Klay Kubiak still in role for 2026.",
        "med",
    ),
    "TB": (
        "Josh Grizzard",
        "1 (2025-)",
        "Coordinator runs offense (Bowles = defensive HC)",
        "Coryell-Canales lineage; play-action vertical",
        "Outside zone with gap complement",
        "11 personnel base",
        "Moderate",
        "Pocket passer (Mayfield)",
        "Vertical / boot red zone",
        "Carroll/Canales tree",
        "Liam Coen / Dave Canales (lineage)",
        "",
        "Kevin Carberry",
        "Internal promotion after Coen left for JAX HC.",
        "",
        "high",
    ),
    "TEN": (
        "Nick Holz",
        "2 (2024-)",
        "HC = architect (Brian Callahan calls plays)",
        "Reid/McVay-adjacent passing",
        "Outside zone primary",
        "11 personnel base",
        "Moderate",
        "Pocket passer (Will Levis / Cam Ward)",
        "Spread red zone",
        "Reid tree (via CIN)",
        "Brian Callahan",
        "",
        "Bill Callahan",
        "Callahan calls plays; OC role admin/QB-room.",
        "Verify retention through 2026.",
        "low",
    ),
    "WAS": (
        "Kliff Kingsbury",
        "2 (2024-)",
        "Coordinator runs offense (Quinn = defensive HC)",
        "Air-Raid spread passing",
        "Outside zone with QB-run; spread",
        "11 personnel heavy",
        "Up-tempo capable",
        "Mobile dual-threat (Jayden Daniels)",
        "Empty / spread / QB-run red zone",
        "Air Raid tree (Mike Leach lineage)",
        "Mike Leach / Kliff's own lineage",
        "",
        "Bobby Engram",
        "Air-Raid OC unlocking Daniels' rookie/sophomore breakout.",
        "",
        "high",
    ),
}

OC_DET = (
    "John Morton",
    "2 (2025-)",
    "Co-coordinator (Campbell trusts him; BJ template)",
    "WCO (Ben Johnson template inheritance)",
    "Outside zone, with power-counter complement",
    "11-heavy (90%+)",
    "Methodical with situational tempo",
    "Pocket passer (Goff)",
    "Creative (BJ legacy of trickery)",
    "Shanahan tree (via Ben Johnson)",
    "Ben Johnson (philosophical inheritance)",
    "Pre-snap motion · Condensed sets · Outside zone · Play-action · TE-heavy red zone",
    "Hank Fraley (zone scheme)",
    "Continuity hire — preserve the Ben Johnson template while Campbell leads from the HC chair.",
    "",
    "high",
)


# ----- DEFENSIVE COORDINATORS ----------------------------------------------
# Tab 3 columns: Name, Years, ArchitectStatus, Coverage, Front, Pressure,
#                PassRush, RunDef, CritSit, Tree, Mentor, SignatureConcepts,
#                OneLiner, Notes, _confidence
DC = {
    "ARI": (
        "Nick Rallis",
        "3 (2023-)",
        "HC = architect (Gannon heavy defensive influence)",
        "Fangio-rooted single-high / quarters hybrid",
        "Multi-front 3-4/4-3 hybrid",
        "Moderate; disguise-heavy",
        "4-man rush primary; situational pressure",
        "Gap-control",
        "Conservative on third-down blitz",
        "Fangio tree (via PHI/ARI)",
        "Jonathan Gannon / Vic Fangio",
        "",
        "Young DC under Gannon's umbrella; Fangio-rooted defense.",
        "",
        "high",
    ),
    "ATL": (
        "Jeff Ulbrich",
        "2 (2025-)",
        "Coordinator runs defense",
        "Pattern-match Cover-3/Quarters",
        "Multi-front 4-3 base",
        "Aggressive blitz capability",
        "Stunts + situational pressure",
        "Gap-control",
        "Multiple-look third-down",
        "Carroll/Saleh tree",
        "Pete Carroll / Robert Saleh",
        "",
        "Saleh-tree DC; aggressive third-down identity.",
        "Verify Ulbrich is current ATL DC for 2026.",
        "med",
    ),
    "BAL": (
        "Zach Orr",
        "3 (2024-)",
        "Coordinator runs defense (Harbaugh = HC)",
        "Disguised single-high / pattern-match",
        "Multi-front (Wink-style 3-4 lineage)",
        "Aggressive blitz / pressure",
        "Multi-rusher pressure",
        "Gap-control",
        "Aggressive critical-down",
        "Harbaugh/Macdonald/Wink tree",
        "Mike Macdonald / Wink Martindale",
        "",
        "Macdonald-tree DC continuing BAL's modern hybrid identity.",
        "",
        "high",
    ),
    "BUF": (
        "Bobby Babich",
        "2 (2024-)",
        "HC = architect (McDermott calls defense)",
        "Quarters / pattern-match",
        "4-3 base",
        "Moderate; situational pressure",
        "4-man rush primary",
        "Gap-control",
        "Bend-don't-break red zone",
        "McDermott tree",
        "Sean McDermott",
        "",
        "Internal promotion under McDermott's defensive system.",
        "",
        "high",
    ),
    "CAR": (
        "Ejiro Evero",
        "3 (2023-)",
        "Coordinator runs defense (Canales = offensive HC)",
        "Fangio-rooted single-high / quarters hybrid",
        "3-4 multi-front",
        "Moderate; disguise-heavy",
        "Mug-look / disguised pressure",
        "Two-gap principles",
        "Conservative third-down blitz",
        "Fangio tree (via DEN)",
        "Vic Fangio",
        "",
        "Fangio-tree DC anchoring CAR's defensive rebuild.",
        "",
        "high",
    ),
    "CHI": (
        "Dennis Allen",
        "1 (2025-)",
        "Coordinator runs defense (Ben Johnson = offensive HC)",
        "Multiple coverage; Cover-1/2/3 hybrid",
        "4-3 base, Wide-9 capable",
        "Aggressive blitz",
        "Edge-rush focused",
        "Gap-control attack",
        "Aggressive critical-down",
        "Payton/Ryan tree (via NO)",
        "Sean Payton / Rob Ryan",
        "",
        "Veteran former HC running CHI's defense under Ben Johnson.",
        "",
        "high",
    ),
    "CIN": (
        "Al Golden",
        "2 (2025-)",
        "Coordinator runs defense (Taylor = offensive HC)",
        "Pattern-match Quarters / multiple",
        "4-3 base",
        "Moderate",
        "4-man rush primary",
        "Gap-control",
        "Mid-pack",
        "Notre Dame / Kelly lineage",
        "Brian Kelly / Marvin Lewis",
        "",
        "Notre Dame DC turned CIN DC; multiple-coverage identity.",
        "",
        "high",
    ),
    "CLE": (
        "Jim Schwartz",
        "3 (2023-)",
        "Coordinator runs defense (Stefanski = offensive HC)",
        "Wide-9 / single-high",
        "4-3 with attack-front Wide-9",
        "Aggressive 4-man rush",
        "Edge-rush dominant (Garrett)",
        "Gap-attack downhill",
        "Aggressive blitz on critical",
        "Schwartz/Belichick tree",
        "Bill Belichick",
        "",
        "Schwartz Wide-9 attack front built around Myles Garrett.",
        "",
        "high",
    ),
    "DAL": (
        "Matt Eberflus",
        "1 (2025-)",
        "Coordinator runs defense (Schottenheimer = offensive HC)",
        "Cover-2 / Tampa-2 lineage",
        "4-3 base",
        "Moderate; situational",
        "4-man rush primary",
        "Gap-control",
        "Conservative critical-down",
        "Tampa-2 / Tomlin tree",
        "Rod Marinelli / Lovie Smith",
        "",
        "Veteran Tampa-2 DC after CHI HC stint.",
        "",
        "high",
    ),
    "DEN": (
        "Vance Joseph",
        "4 (2023-)",
        "Coordinator runs defense (Payton = offensive HC)",
        "Multiple; Cover-1/3 hybrid",
        "3-4 multi-front",
        "Aggressive blitz",
        "Mug-look / multi-rusher",
        "Gap-control",
        "Aggressive critical-down",
        "Wade Phillips / Dom Capers tree",
        "Wade Phillips",
        "",
        "Veteran DC; anchoring DEN's top-tier defense.",
        "",
        "high",
    ),
    "DET": None,  # canonical row below
    "GB": (
        "Jeff Hafley",
        "2 (2024-)",
        "Coordinator runs defense (LaFleur = offensive HC)",
        "Quarters-heavy single-high hybrid",
        "4-3 base",
        "Moderate; situational pressure",
        "4-man rush primary",
        "Gap-control",
        "Pattern-match critical-down",
        "Pittsburgh/BC lineage",
        "Pat Narduzzi (philosophical)",
        "",
        "College DC turned GB DC; quarters-heavy modernization.",
        "",
        "high",
    ),
    "HOU": (
        "Matt Burke",
        "2 (2025-)",
        "HC = architect (Ryans heavy defensive influence)",
        "Cover-3 single-high / pattern-match",
        "4-3 Wide-9 attack",
        "Moderate; edge-rush dominant",
        "Edge-rush focused (Anderson/Hunter)",
        "Gap-attack",
        "Mid-pack",
        "Saleh/Shanahan tree",
        "DeMeco Ryans / Robert Saleh",
        "",
        "Saleh-tree DC under Ryans' defensive identity.",
        "",
        "med",
    ),
    "IND": (
        "Lou Anarumo",
        "2 (2025-)",
        "Coordinator runs defense (Steichen = offensive HC)",
        "Multiple coverage; disguised hybrid",
        "4-3 base",
        "Moderate",
        "Mug-look / disguised",
        "Gap-control",
        "Disguised critical-down",
        "Marvin Lewis / Bengals lineage",
        "Marvin Lewis",
        "",
        "Former CIN DC; disguised hybrid defense for IND.",
        "",
        "high",
    ),
    "JAX": (
        "Anthony Campanile",
        "1 (2025-)",
        "Coordinator runs defense (Coen = offensive HC)",
        "Multi-coverage hybrid",
        "Multi-front 3-4/4-3 hybrid",
        "Aggressive disguise",
        "Multi-rusher pressure",
        "Gap-control",
        "Aggressive critical-down",
        "Belichick/Patricia tree (NE/MIA)",
        "Mike Vrabel / Bill Belichick",
        "",
        "BB-lineage DC paired with Coen's offense in JAX.",
        "",
        "med",
    ),
    "KC": (
        "Steve Spagnuolo",
        "7 (2019-)",
        "Coordinator runs defense (Reid = offensive HC)",
        "Multi-coverage with heavy disguise",
        "4-3 base",
        "Aggressive blitz",
        "Mug-look / Spags-blitz",
        "Gap-control",
        "Famously aggressive critical-down (SB blitz)",
        "Spagnuolo tree (Giants 2007 lineage)",
        "Bill Parcells / Tom Coughlin",
        "",
        "Multiple-SB DC; defining critical-down blitz architect.",
        "",
        "high",
    ),
    "LA": (
        "Chris Shula",
        "2 (2024-)",
        "Coordinator runs defense (McVay = offensive HC)",
        "Multi-coverage (Brandon Staley lineage)",
        "Multi-front",
        "Aggressive blitz capable",
        "Stunts / mug-look",
        "Gap-control",
        "Aggressive third-down",
        "Vic Fangio tree (LA staff lineage)",
        "Raheem Morris (former LA DC)",
        "",
        "Internal promotion under McVay; Fangio-tree continuity.",
        "",
        "high",
    ),
    "LAC": (
        "Jesse Minter",
        "2 (2024-)",
        "Coordinator runs defense (Harbaugh = HC)",
        "Pattern-match Quarters / hybrid",
        "Multi-front 3-4/4-3 hybrid",
        "Aggressive disguise",
        "Multi-rusher pressure (Bosa/Mack)",
        "Gap-control",
        "Aggressive critical-down",
        "Harbaugh/Macdonald tree",
        "Mike Macdonald",
        "",
        "Macdonald-tree DC reunited with Harbaugh from MICH.",
        "",
        "high",
    ),
    "LV": (
        "Patrick Graham",
        "5 (2022-)",
        "HC = architect (Carroll heavy defensive influence)",
        "Multiple coverage; disguised",
        "Multi-front 3-4/4-3 hybrid",
        "Moderate-to-aggressive",
        "Mug-look / disguised",
        "Gap-control",
        "Disguised critical-down",
        "Belichick tree",
        "Bill Belichick",
        "",
        "BB-tree DC kept on through Carroll era.",
        "Verify retention through 2026.",
        "med",
    ),
    "MIA": (
        "Anthony Weaver",
        "2 (2024-)",
        "Coordinator runs defense (McDaniel = offensive HC)",
        "Multi-coverage hybrid",
        "Multi-front 3-4/4-3 hybrid",
        "Moderate; situational pressure",
        "Edge-rush dominant",
        "Gap-control",
        "Mid-pack",
        "Belichick/Ryans tree",
        "Bill Belichick / DeMeco Ryans",
        "",
        "Belichick/Ryans-tree DC anchoring MIA defense.",
        "",
        "high",
    ),
    "MIN": (
        "Brian Flores",
        "3 (2023-)",
        "Coordinator runs defense (O'Connell = offensive HC)",
        "Cover-0/1 with heavy mug-blitz",
        "Multi-front 3-4 hybrid",
        "Top-tier blitz rate",
        "Cover-0 / mug-look pressure",
        "Gap-attack",
        "Famously aggressive critical-down",
        "Belichick tree",
        "Bill Belichick",
        "",
        "Belichick-tree DC running league's most aggressive blitz scheme.",
        "",
        "high",
    ),
    "NE": (
        "Terrell Williams",
        "2 (2025-)",
        "HC = architect (Vrabel heavy defensive influence)",
        "Multiple coverage hybrid",
        "Multi-front 3-4/4-3 hybrid",
        "Moderate-to-aggressive",
        "Edge-rush focused",
        "Gap-control",
        "Disguised critical-down",
        "Vrabel/TEN tree",
        "Mike Vrabel",
        "",
        "Vrabel-tree DC in NE; defensive HC pairing.",
        "",
        "high",
    ),
    "NO": (
        "Brandon Staley",
        "1 (2025-)",
        "Coordinator runs defense (Moore = offensive HC)",
        "Fangio-rooted single-high / quarters hybrid",
        "3-4 multi-front",
        "Moderate; disguise-heavy",
        "4-man rush primary",
        "Gap-control",
        "Conservative critical-down",
        "Fangio tree",
        "Vic Fangio",
        "",
        "Fangio-tree former HC reset under Moore in NO.",
        "Verify retention; possible Joe Woods alternative.",
        "med",
    ),
    "NYG": (
        "Shane Bowen",
        "3 (2024-)",
        "Coordinator runs defense (Daboll = offensive HC)",
        "Multiple coverage with Cover-3 base",
        "4-3 multi-front",
        "Moderate; situational pressure",
        "Edge-rush focused",
        "Gap-control",
        "Mid-pack",
        "Vrabel/TEN tree",
        "Mike Vrabel",
        "",
        "Vrabel-tree DC inherited by Daboll.",
        "Verify retention through 2026.",
        "low",
    ),
    "NYJ": (
        "Steve Wilks",
        "1 (2025-)",
        "Coordinator runs defense (Glenn = defensive HC)",
        "Multi-coverage hybrid",
        "4-3 base",
        "Moderate-to-aggressive",
        "Edge-rush focused",
        "Gap-control",
        "Aggressive critical-down",
        "Carolina/CAR lineage",
        "Aaron Glenn",
        "",
        "Veteran DC under Glenn's defensive HC umbrella.",
        "Verify Wilks is the actual NYJ DC.",
        "low",
    ),
    "PHI": (
        "Vic Fangio",
        "2 (2024-)",
        "Coordinator runs defense (Sirianni = offensive HC)",
        "Fangio single-high / quarters hybrid (root)",
        "3-4 / 4-3 hybrid; light boxes",
        "Moderate; disguise-heavy",
        "4-man rush primary",
        "Gap-control",
        "Conservative critical-down (drop-8 capable)",
        "Fangio tree (root)",
        "Dom Capers (philosophical)",
        "",
        "The namesake Fangio scheme architect; reigning SB DC.",
        "",
        "high",
    ),
    "PIT": (
        "Teryl Austin",
        "5 (2022-)",
        "HC = architect (Tomlin heavy defensive influence)",
        "Multi-coverage with Cover-2/3 base",
        "3-4 base (zone blitz lineage)",
        "Aggressive blitz",
        "Zone-blitz / mug-look",
        "Gap-control",
        "Aggressive critical-down",
        "Dick LeBeau / Tomlin tree",
        "Dick LeBeau / Mike Tomlin",
        "",
        "Tomlin's longtime DC; LeBeau-zone-blitz lineage.",
        "",
        "high",
    ),
    "SEA": (
        "Aden Durde",
        "2 (2024-)",
        "HC = architect (Macdonald defensive HC)",
        "Pattern-match hybrid",
        "Multi-front 3-4/4-3 hybrid",
        "Aggressive disguise",
        "Multi-rusher pressure",
        "Gap-control",
        "Aggressive critical-down",
        "Macdonald tree",
        "Mike Macdonald",
        "",
        "DC under Macdonald's defensive identity.",
        "",
        "high",
    ),
    "SF": (
        "Robert Saleh",
        "2 (2025-)",
        "Coordinator runs defense (Shanahan = offensive HC)",
        "Cover-3 single-high / quarters",
        "4-3 Wide-9 attack",
        "Moderate; edge-rush dominant",
        "Edge-rush dominant (Bosa)",
        "Gap-attack",
        "Mid-pack",
        "Saleh/Shanahan tree (root co-equal)",
        "Pete Carroll / Gus Bradley",
        "",
        "Returning DC after NYJ HC stint; SF Wide-9 architect.",
        "",
        "high",
    ),
    "TB": (
        "Kacy Rodgers",
        "1 (2025-)",
        "HC = architect (Bowles heavy defensive influence)",
        "Cover-1/2 hybrid",
        "Multi-front 3-4 hybrid",
        "Top-tier blitz rate",
        "Mug-look / multi-rusher pressure",
        "Gap-attack",
        "Aggressive critical-down",
        "Bowles tree",
        "Todd Bowles",
        "",
        "Bowles-tree DC; blitz-heavy identity continues.",
        "Verify exact DC of record.",
        "med",
    ),
    "TEN": (
        "Dennard Wilson",
        "2 (2024-)",
        "Coordinator runs defense (Callahan = offensive HC)",
        "Pattern-match Quarters",
        "Multi-front 4-3 base",
        "Moderate; situational",
        "4-man rush primary",
        "Gap-control",
        "Mid-pack",
        "Harbaugh/Macdonald tree",
        "Mike Macdonald",
        "",
        "Macdonald-tree DC anchoring TEN's defensive rebuild.",
        "",
        "high",
    ),
    "WAS": (
        "Joe Whitt Jr.",
        "2 (2024-)",
        "HC = architect (Quinn heavy defensive influence)",
        "Cover-3 single-high / pattern-match",
        "Multi-front 4-3 base",
        "Aggressive blitz",
        "Edge-rush focused",
        "Gap-attack",
        "Aggressive critical-down",
        "Quinn/Carroll tree",
        "Dan Quinn",
        "",
        "Quinn-tree DC running WAS's aggressive defense.",
        "",
        "high",
    ),
}

DC_DET = (
    "Kelvin Sheppard",
    "2 (2025-)",
    "Dedicated",
    "Cover-3 base / pattern-match (AG inheritance)",
    "Multiple (4-3 base, sub-package heavy)",
    "Disguised pressure, 4-man rush primary",
    "Stunts/twists; Hutchinson speed off the edge",
    "Gap-control, attack-style",
    "Cover-2 in red zone; rare 3rd-and-long blitz",
    "Glenn tree (Saints/Falcons/Lions lineage)",
    "Aaron Glenn (philosophical inheritance)",
    "Disguised single-high · Mug looks · Hutchinson/AA edge speed · Hybrid LB roles",
    "Continuity hire after Glenn → NYJ HC. Preserves the Glenn defensive identity.",
    "",
    "high",
)


# ----- GENERAL MANAGERS -----------------------------------------------------
# Tab 4 columns: Name, Years, RosterPhilosophy, CapAlloc, PositionPriority,
#                DraftTendencies, RiskTolerance, MentorSchool, CareerPath,
#                NotableHits, OneLiner, Notes, _confidence
GM = {
    "ARI": (
        "Monti Ossenfort",
        "4 (2023-)",
        "Trade-down / accumulate-picks rebuild",
        "Mid-cap; preserved flex through rebuild",
        "Trenches and DB",
        "BPA with quantity tilt",
        "Moderate",
        "Belichick tree (NE personnel) / Titans lineage",
        "NE scout → TEN dir of college → ARI GM",
        "Hits: Marvin Harrison Jr. drafting, Conner extension",
        "Belichick-tree GM rebuilding ARI through volume drafting.",
        "",
        "high",
    ),
    "ATL": (
        "Terry Fontenot",
        "6 (2021-)",
        "Skill-position-heavy build with mid-FA splash",
        "Top-heavy stars (Cousins/Penix split)",
        "Skill positions (Bijon, London, Pitts)",
        "Skill-position bias",
        "Moderate-to-high (Cousins/Penix double-dip)",
        "Saints/Loomis tree",
        "NO scout asst → NO pro scouting → ATL GM",
        "Hits: Bijon, London, Penix bet. Misses: Pitts ROI",
        "Saints-tree GM with skill-position-first roster identity.",
        "",
        "high",
    ),
    "BAL": (
        "Eric DeCosta",
        "7 (2019-)",
        "Compensatory-pick exploitation; trenches+DB build",
        "Lamar-extension flex management",
        "Trenches and DB",
        "BPA with comp-pick optimization",
        "Moderate",
        "Ozzie Newsome tree / BAL lineage",
        "BAL scout (1996-) → BAL GM",
        "Hits: Stanley, Hamilton, Likely. Misses: 2018 WR class",
        "Ozzie-tree GM mastering the compensatory-pick game.",
        "",
        "high",
    ),
    "BUF": (
        "Brandon Beane",
        "9 (2017-)",
        "Allen-extension flex; aggressive cap mgmt",
        "Top-heavy (Allen/Diggs prior)",
        "Trenches and DB",
        "Trenches/DB tilt; trade-up willing",
        "Moderate-to-high",
        "Carolina/Hurney tree",
        "CAR scout → CAR pro scouting → BUF GM",
        "Hits: Allen, Milano. Misses: Cody Ford, Jamarcus Davis",
        "Hurney-tree GM aggressive in cap restructures around Allen.",
        "",
        "high",
    ),
    "CAR": (
        "Dan Morgan",
        "3 (2024-)",
        "Trenches-first rebuild after 2023 trade-up",
        "Mid-cap; restoring flex",
        "OL and pass-rush",
        "Trenches tilt",
        "Moderate",
        "Buffalo/Beane tree",
        "BUF dir of player personnel → CAR GM",
        "Hits: 2024 D draft. Misses: pre-tenure (Bryce trade-up)",
        "Beane-tree GM resetting CAR after Bryce Young trade-up fallout.",
        "",
        "high",
    ),
    "CHI": (
        "Ryan Poles",
        "5 (2022-)",
        "Draft-and-develop with cap-flex preservation",
        "Mid-cap; built up draft capital",
        "WR/OL early; D-line build-up",
        "Trade-down willing; BPA",
        "Moderate",
        "Chiefs/Veach tree",
        "KC scout → KC personnel → CHI GM",
        "Hits: 2024 WR class, Caleb pick. Misses: Velus Jones",
        "Chiefs-tree GM rebuilding CHI through draft capital and Caleb era.",
        "",
        "high",
    ),
    "CIN": (
        "Duke Tobin",
        "3 (2024-, formal title)",
        "Conservative cap mgmt; Burrow extension flex",
        "Top-heavy (Burrow/Chase/Higgins)",
        "Skill positions and DL",
        "BPA",
        "Low (CIN historic risk-averse)",
        "Bengals organic / Brown family lineage",
        "CIN scout → CIN dir of personnel → CIN de facto/formal GM",
        "Hits: Burrow, Chase. Misses: 2022 D-line investments",
        "Long-time CIN personnel chief now formally GM.",
        "Verify exact title status / years.",
        "med",
    ),
    "CLE": (
        "Andrew Berry",
        "7 (2020-)",
        "Analytics-forward; Watson trade still defining",
        "Top-heavy (Watson + others)",
        "DL and DB",
        "Analytics-driven BPA with positional value",
        "High (Watson trade)",
        "Browns/Eagles analytics tree",
        "CLE/PHI scouting → CLE GM",
        "Hits: Garrett extension, Wills. Misses: Watson trade",
        "Analytics-forward GM operating under Watson-trade gravity.",
        "",
        "high",
    ),
    "DAL": (
        "Jerry Jones",
        "37 (1989-)",
        "Owner-GM; star-driven build",
        "Top-heavy stars (Dak/Lamb/Parsons)",
        "Skill and trenches",
        "BPA with star tilt",
        "Moderate (extensions late)",
        "N/A (owner)",
        "Owner-GM since 1989",
        "Hits: 1990s dynasty. Misses: late-extension cap drama",
        "The owner-GM; longest-tenured front-office decision-maker.",
        "Will McClay heavily influences personnel; verify title hierarchy.",
        "high",
    ),
    "DEN": (
        "George Paton",
        "6 (2021-)",
        "Cap-flex mgmt around Wilson dead-money + Payton install",
        "Top-heavy (Bo Nix dev era)",
        "DB and DL",
        "BPA",
        "Moderate",
        "Vikings/Spielman tree",
        "MIA/CHI/MIN personnel → DEN GM",
        "Hits: Surtain, Bolles. Misses: Wilson trade",
        "Vikings-tree GM working through Wilson trade and Payton era.",
        "",
        "high",
    ),
    "DET": None,  # canonical row
    "GB": (
        "Brian Gutekunst",
        "9 (2018-)",
        "Draft-and-develop; FA-allergic by reputation",
        "Mid-cap; QB-extension flex (Love)",
        "DL and DB",
        "Trade-up willing on premium positions",
        "Moderate (Rodgers trade)",
        "Wolf/Thompson tree (GB lineage)",
        "GB scout (1998-) → GB GM",
        "Hits: Jaire, Bakhtiari. Misses: Love selection year (justified later)",
        "GB-organic GM mastering draft-and-extend with Love era.",
        "",
        "high",
    ),
    "HOU": (
        "Nick Caserio",
        "6 (2021-)",
        "Belichick-volume; rapid roster turnover",
        "Top-heavy (Stroud rookie deal flex)",
        "WR and DB",
        "Volume drafting; BPA",
        "Moderate",
        "Belichick tree (NE)",
        "NE personnel (1998-2020) → HOU GM",
        "Hits: Stroud, Anderson. Misses: WR free-agency churn",
        "Belichick-tree GM mid-rebuild around Stroud's rookie window.",
        "",
        "high",
    ),
    "IND": (
        "Chris Ballard",
        "10 (2017-)",
        "Draft-and-develop; FA-allergic",
        "Mid-cap; preserved flex through rebuild",
        "DL and OL",
        "Trenches tilt; BPA",
        "Low-to-moderate",
        "Polian/Chiefs tree",
        "CHI/KC personnel → IND GM",
        "Hits: Quenton Nelson, Leonard. Misses: QB churn (Wentz/Ryan)",
        "Chiefs-tree GM defined by trenches investment and QB-room churn.",
        "",
        "high",
    ),
    "JAX": (
        "James Gladstone",
        "1 (2025-)",
        "Trade-down / accumulate / Rams-style rebuild",
        "Mid-cap reset",
        "DB and OL",
        "Trade-down willing",
        "Moderate",
        "McVay/Snead tree (Rams)",
        "LA Rams scouting (2014-) → JAX GM",
        "Hits: TBD (early). Misses: TBD",
        "Rams-tree young GM resetting JAX with Coen and Lawrence.",
        "",
        "high",
    ),
    "KC": (
        "Brett Veach",
        "9 (2017-)",
        "Star-driven; Mahomes-extension flex mgmt",
        "Top-heavy (Mahomes/Kelce/etc.)",
        "WR and DB (post-2023)",
        "BPA with star tilt",
        "Moderate-to-high",
        "Reid/Dorsey tree",
        "PHI personnel → KC personnel → KC GM",
        "Hits: Mahomes era roster. Misses: 2022 WR investments",
        "Reid-tree GM running the dynasty roster around Mahomes.",
        "",
        "high",
    ),
    "LA": (
        "Les Snead",
        "14 (2012-)",
        "F*** them picks; Stafford-era star acquisition",
        "Top-heavy stars (Stafford/Kupp/Donald past)",
        "DL and WR",
        "Trade-up willing; star-acquisition tilt",
        "High (signature trade-up philosophy)",
        "ATL/Dimitroff tree",
        "ATL personnel → LA GM",
        "Hits: SB LVI, Stafford trade. Misses: WR depth churn",
        "F***-them-picks GM; defined the star-trade-up era for LA.",
        "",
        "high",
    ),
    "LAC": (
        "Joe Hortiz",
        "3 (2024-)",
        "Trenches-first build aligned with Harbaugh identity",
        "Mid-cap; resetting flex",
        "OL and DL",
        "Trenches tilt; BPA",
        "Moderate",
        "Ravens/DeCosta tree",
        "BAL scouting (1998-) → LAC GM",
        "Hits: TBD (early). Misses: TBD",
        "Ravens-tree GM aligned with Harbaugh's downhill identity.",
        "",
        "high",
    ),
    "LV": (
        "John Spytek",
        "1 (2025-)",
        "Trenches-first rebuild",
        "Mid-cap reset",
        "DL and OL",
        "Trenches tilt; BPA",
        "Moderate",
        "Buccaneers/Licht tree",
        "TB personnel (2016-) → LV GM",
        "Hits: TBD (early). Misses: TBD",
        "Bucs-tree GM resetting LV under Carroll era.",
        "",
        "high",
    ),
    "MIA": (
        "Chris Grier",
        "10 (2016-)",
        "Star-acquisition with Tua-extension flex",
        "Top-heavy (Tua/Hill/Waddle)",
        "WR and DB",
        "Trade-up willing on premium positions",
        "Moderate-to-high",
        "Bills/Polian tree",
        "MIA scout (2000-) → MIA GM",
        "Hits: Hill trade, Waddle. Misses: McDaniel-era OL/D investment",
        "Long-tenured MIA GM defined by Tyreek trade and skill-position build.",
        "",
        "high",
    ),
    "MIN": (
        "Kwesi Adofo-Mensah",
        "5 (2022-)",
        "Analytics-forward; QB churn flex",
        "Mid-cap; preserved flex through Cousins/Darnold/McCarthy era",
        "WR and DB",
        "Analytics BPA",
        "Moderate (J.J. McCarthy trade-up)",
        "Browns/SF analytics tree",
        "SF/CLE analytics → MIN GM",
        "Hits: Jefferson extension, Hockenson trade. Misses: 2022 D",
        "Analytics GM navigating Cousins-McCarthy QB transition.",
        "",
        "high",
    ),
    "NE": (
        "Eliot Wolf",
        "2 (2024-)",
        "Belichick-system reset; trenches build",
        "Mid-cap; Drake Maye rookie window",
        "OL and DB",
        "BPA with trenches tilt",
        "Moderate",
        "Wolf tree (GB lineage) / Belichick organic",
        "GB/CLE/NE personnel → NE GM",
        "Hits: Drake Maye selection. Misses: TBD",
        "Wolf-tree exec running NE rebuild post-Belichick.",
        "",
        "high",
    ),
    "NO": (
        "Mickey Loomis",
        "24 (2002-)",
        "Cap-restructure mastery; aggressive star retention",
        "Top-heavy (perpetual restructures)",
        "Skill and DL",
        "BPA with cap acrobatics",
        "High (cap pushes)",
        "Saints organic",
        "NO personnel (1985-) → NO GM",
        "Hits: SB XLIV roster. Misses: post-Brees QB churn",
        "Cap-restructure architect; longest-tenured GM behind Jerry Jones.",
        "",
        "high",
    ),
    "NYG": (
        "Joe Schoen",
        "5 (2022-)",
        "Trenches build; QB-room reset",
        "Mid-cap reset",
        "OL and DL",
        "BPA with trenches tilt",
        "Moderate",
        "Bills/Beane tree",
        "BUF asst GM → NYG GM",
        "Hits: Thibodeaux. Misses: Daniel Jones extension, WR investment",
        "Beane-tree GM defined by Daniel Jones extension and reset.",
        "Verify retention through 2026.",
        "low",
    ),
    "NYJ": (
        "Darren Mougey",
        "2 (2025-)",
        "Trenches/DB rebuild aligned with Glenn",
        "Mid-cap reset",
        "DL and DB",
        "BPA",
        "Moderate",
        "Broncos/Paton tree",
        "DEN scouting → NYJ GM",
        "Hits: TBD (early). Misses: TBD",
        "Broncos-tree GM rebuilding NYJ under Glenn HC era.",
        "",
        "high",
    ),
    "PHI": (
        "Howie Roseman",
        "16 (2010-, with gap)",
        "Trenches-first; star-extension flex",
        "Top-heavy stars",
        "OL and DL",
        "Trenches tilt; trade-up willing on trenches",
        "High (multiple star trades)",
        "Eagles organic",
        "PHI organic (2000-) → PHI GM",
        "Hits: SB LII/LIX rosters. Misses: 2020 draft class",
        "Roseman is the gold-standard trenches GM; 2x SB roster builder.",
        "",
        "high",
    ),
    "PIT": (
        "Omar Khan",
        "4 (2022-)",
        "Conservative cap mgmt; trenches build",
        "Mid-cap; Rooney-rule fiscal discipline",
        "OL and DL",
        "BPA with trenches tilt",
        "Moderate",
        "Steelers organic / Colbert tree",
        "PIT organic (2001-) → PIT GM",
        "Hits: Heyward extension. Misses: Pickett selection",
        "Steelers-organic GM continuing the Colbert trenches identity.",
        "",
        "high",
    ),
    "SEA": (
        "John Schneider",
        "16 (2010-)",
        "Trade-down / accumulate; Carroll-aligned rebuild",
        "Mid-cap reset",
        "DL and DB",
        "Trade-down willing",
        "Moderate-to-high",
        "Wolf tree (GB) / Carroll-aligned",
        "GB scouting → WAS → SEA GM",
        "Hits: LOB era. Misses: post-Wilson D-line investment",
        "Long-tenured GM mastering trade-down and rebuild cycles.",
        "",
        "high",
    ),
    "SF": (
        "John Lynch",
        "10 (2017-)",
        "Star-acquisition with Shanahan-aligned roster build",
        "Top-heavy stars (Bosa/Williams/etc.)",
        "DL and OL",
        "Trade-up willing; trenches tilt",
        "High",
        "FOX broadcast → Shanahan partnership",
        "TB safety → FOX → SF GM",
        "Hits: Bosa, Purdy. Misses: Lance trade-up",
        "HOF safety turned star-acquisition GM aligned with Shanahan.",
        "",
        "high",
    ),
    "TB": (
        "Jason Licht",
        "12 (2014-)",
        "Star-retention; cap-restructure mastery",
        "Top-heavy stars (Mayfield/Evans/Wirfs)",
        "OL and WR",
        "BPA with star tilt",
        "Moderate",
        "Patriots/Eagles lineage",
        "PHI/NE/ARI personnel → TB GM",
        "Hits: SB LV roster. Misses: post-Brady QB transition",
        "Long-tenured GM defined by Brady SB and post-Brady stability.",
        "",
        "high",
    ),
    "TEN": (
        "Mike Borgonzi",
        "1 (2025-)",
        "Trenches/skill rebuild",
        "Mid-cap reset",
        "DL and WR",
        "BPA",
        "Moderate",
        "Chiefs/Veach tree",
        "KC personnel (2009-) → TEN GM",
        "Hits: TBD (early). Misses: TBD",
        "Chiefs-tree young GM rebuilding TEN.",
        "",
        "high",
    ),
    "WAS": (
        "Adam Peters",
        "3 (2024-)",
        "Trenches-first; Daniels rookie window flex",
        "Mid-cap; Daniels rookie deal preserves flex",
        "OL and DL",
        "BPA with trenches tilt",
        "Moderate",
        "49ers/Lynch tree",
        "DEN/SF personnel → WAS GM",
        "Hits: Jayden Daniels selection, Tunsil trade. Misses: TBD",
        "49ers-tree GM running the Daniels-Quinn era reset.",
        "",
        "high",
    ),
}

GM_DET = (
    "Brad Holmes",
    "5 (2021-)",
    "Draft-and-develop with selective FA splash",
    "Top-heavy stars + drafted depth",
    "OL-first / DL second",
    "BPA with positional value tilt to trenches",
    "Production over measurables; willing on character risks",
    "Howie Roseman (philosophical) / Rams scout dept",
    "STL/LA Rams scout (1995-2020) → DET GM",
    "Hits: Hutchinson, Sewell, Gibbs, LaPorta, ARSB. Misses: Okwara extension, Levi Onwuzurike",
    "Built the Lions' transformation through scouting depth and trench investment.",
    "",
    "high",
)


# ---------------------------------------------------------------------------
# WORKBOOK BUILD
# ---------------------------------------------------------------------------

def _make_header_row(ws, row_idx, headers, fill=HEADER_FILL, font=HEADER_FONT):
    for col_idx, h in enumerate(headers, start=1):
        cell = ws.cell(row=row_idx, column=col_idx, value=h)
        cell.fill = fill
        cell.font = font
        cell.alignment = Alignment(
            horizontal="left", vertical="center", wrap_text=True)
        cell.border = CELL_BORDER


def _set_widths(ws, widths):
    for col_idx, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(col_idx)].width = w


def _add_title(ws, title, n_cols):
    ws.merge_cells(start_row=1, start_column=1,
                   end_row=1, end_column=n_cols)
    cell = ws.cell(row=1, column=1, value=title)
    cell.fill = TITLE_FILL
    cell.font = TITLE_FONT
    cell.alignment = Alignment(horizontal="center", vertical="center")


def _fill_proposed_row(ws, row_idx, team, values_with_conf, det_row=None):
    """Write team row. RED font for proposals, BLACK for DET canonical.

    values_with_conf: tuple where last element is the _confidence string.
    det_row: if provided (DET only), values are written in default BLACK.
    """
    # Team code in default font
    ws.cell(row=row_idx, column=1, value=team)

    if det_row is not None:
        # DET canonical row — black font, with EXAMPLE_FILL highlight
        for col_idx, val in enumerate(det_row, start=2):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.fill = EXAMPLE_FILL
        # Highlight team cell too
        ws.cell(row=row_idx, column=1).fill = EXAMPLE_FILL
        return

    if values_with_conf is None:
        return

    for col_idx, val in enumerate(values_with_conf, start=2):
        cell = ws.cell(row=row_idx, column=col_idx, value=val)
        cell.font = PROPOSAL_FONT


def _build_hc_tab(wb):
    ws = wb.create_sheet("Head Coach")
    headers = [
        "Team", "Name", "Years in role",
        "System / identity",
        "Coaching tree / school",
        "Mentor (primary)",
        "Career path",
        "Leadership archetype",
        "4th-down aggression",
        "Game-management rep",
        "Acts as OC?",
        "Acts as DC?",
        "Signature win / moment",
        "One-liner identity",
        "Notes",
        "_confidence",
    ]
    n_cols = len(headers)
    _add_title(ws, "HEAD COACH — proposals (red = agent-suggested)", n_cols)
    _make_header_row(ws, 2, headers)
    _set_widths(ws, [
        8, 22, 8, 30, 28, 22, 38, 28, 18, 38,
        12, 12, 38, 50, 30, 14,
    ])
    ws.freeze_panes = "C3"

    for i, t in enumerate(TEAMS):
        r = 3 + i
        if t == "DET":
            _fill_proposed_row(ws, r, t, None, det_row=HC_DET)
        else:
            _fill_proposed_row(ws, r, t, HC[t])

    return ws


def _build_oc_tab(wb):
    ws = wb.create_sheet("Offensive Coordinator")
    headers = [
        "Team", "Name", "Years in role",
        "Architect status",
        "Passing system",
        "Running system",
        "Personnel preference",
        "Pace identity",
        "QB type designed for",
        "Red-zone identity",
        "Coaching tree",
        "Mentor (primary)",
        "Signature concepts",
        "OL coach (architect of run game)",
        "One-liner identity",
        "Notes",
        "_confidence",
    ]
    n_cols = len(headers)
    _add_title(ws,
               "OFFENSIVE COORDINATOR — proposals "
               "(if HC is architect, status=\"HC = architect\")",
               n_cols)
    _make_header_row(ws, 2, headers)
    _set_widths(ws, [
        8, 22, 8, 22,
        24, 26, 22, 18, 18, 22, 22, 22, 50,
        22, 50, 30, 14,
    ])
    ws.freeze_panes = "C3"

    for i, t in enumerate(TEAMS):
        r = 3 + i
        if t == "DET":
            _fill_proposed_row(ws, r, t, None, det_row=OC_DET)
        else:
            _fill_proposed_row(ws, r, t, OC[t])

    return ws


def _build_dc_tab(wb):
    ws = wb.create_sheet("Defensive Coordinator")
    headers = [
        "Team", "Name", "Years in role",
        "Architect status",
        "Coverage scheme",
        "Front structure",
        "Pressure tendencies",
        "Pass-rush plan",
        "Run defense identity",
        "Critical-situation tendency",
        "Coaching tree",
        "Mentor (primary)",
        "Signature concepts",
        "One-liner identity",
        "Notes",
        "_confidence",
    ]
    n_cols = len(headers)
    _add_title(ws,
               "DEFENSIVE COORDINATOR — proposals "
               "(if HC is architect, status=\"HC = architect\")",
               n_cols)
    _make_header_row(ws, 2, headers)
    _set_widths(ws, [
        8, 22, 8, 22, 26, 18, 26, 26, 24, 32, 22, 22, 50, 50, 30, 14,
    ])
    ws.freeze_panes = "C3"

    for i, t in enumerate(TEAMS):
        r = 3 + i
        if t == "DET":
            _fill_proposed_row(ws, r, t, None, det_row=DC_DET)
        else:
            _fill_proposed_row(ws, r, t, DC[t])

    return ws


def _build_gm_tab(wb):
    ws = wb.create_sheet("General Manager")
    headers = [
        "Team", "Name", "Years in role",
        "Roster-build philosophy",
        "Cap allocation",
        "Position-group priority",
        "Draft tendencies",
        "Risk tolerance",
        "Mentor / school",
        "Career path",
        "Notable hits / misses",
        "One-liner identity",
        "Notes",
        "_confidence",
    ]
    n_cols = len(headers)
    _add_title(ws, "GENERAL MANAGER — proposals", n_cols)
    _make_header_row(ws, 2, headers)
    _set_widths(ws, [
        8, 22, 8, 26, 24, 26, 24, 22, 26, 38, 50, 50, 30, 14,
    ])
    ws.freeze_panes = "C3"

    for i, t in enumerate(TEAMS):
        r = 3 + i
        if t == "DET":
            _fill_proposed_row(ws, r, t, None, det_row=GM_DET)
        else:
            _fill_proposed_row(ws, r, t, GM[t])

    return ws


def _summarize(tabs_data):
    """Print confidence + cell-fill summary."""
    total_cells = 0
    conf_counts = {"high": 0, "med": 0, "low": 0,
                   "judgment_needed": 0, "blank": 0}
    unconfirmed_hc = []

    for tab_name, data, det_present in tabs_data:
        for team, row in data.items():
            if row is None:
                continue
            *vals, conf = row
            for v in vals:
                if v not in (None, ""):
                    total_cells += 1
            conf_key = (conf or "").strip()
            if conf_key == "":
                conf_counts["blank"] += 1
            elif conf_key in conf_counts:
                conf_counts[conf_key] += 1
            else:
                conf_counts["blank"] += 1
            if tab_name == "HC" and conf_key in ("low", "blank", ""):
                unconfirmed_hc.append((team, row[0]))

    print(f"Total proposed cells filled: {total_cells}")
    print("Confidence distribution (per row):")
    for k, v in conf_counts.items():
        print(f"  {k:18s} {v}")
    if unconfirmed_hc:
        print("HCs with low/blank confidence (2026 status uncertain):")
        for t, name in unconfirmed_hc:
            print(f"  {t:4s} {name}")
    else:
        print("All 31 non-DET HCs confirmed at med-or-better confidence.")


def main() -> None:
    wb = Workbook()
    wb.remove(wb.active)

    _build_hc_tab(wb)
    _build_oc_tab(wb)
    _build_dc_tab(wb)
    _build_gm_tab(wb)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    wb.save(OUT)
    print(f"Wrote {OUT.relative_to(REPO)}")
    print("4 tabs: Head Coach / Offensive Coordinator / "
          "Defensive Coordinator / General Manager")
    print("32 team rows per tab, alphabetical")
    print("DET row in BLACK (canonical, from Brett's example).")
    print("All other team rows in RED (agent-proposed).")
    print()
    _summarize([
        ("HC", HC, True),
        ("OC", OC, True),
        ("DC", DC, True),
        ("GM", GM, True),
    ])


if __name__ == "__main__":
    main()
